const EmployeeActionTypes = {
  LOGIN_EMPLOYEE_START: "LOGIN_EMPLOYEE_START",
  LOGIN_EMPLOYEE_SUCCESS: "LOGIN_EMPLOYEE_SUCCESS",
  LOGIN_EMPLOYEE_FAILURE: "LOGIN_EMPLOYEE_FAILURE",

  LOGOUT_EMPLOYEE_START: "LOGOUT_EMPLOYEE_START",
  LOGOUT_EMPLOYEE_SUCCESS: "LOGOUT_EMPLOYEE_SUCCESS",
  LOGOUT_EMPLOYEE_FAILURE: "LOGOUT_EMPLOYEE_FAILURE",
};

export default EmployeeActionTypes;
