const CartActionTypes = {
  ADD_TO_CART_START: "ADD_TO_CART_START",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  REMOVE_FROM_CART_START: "REMOVE_FROM_CART_START",
  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAILURE: "REMOVE_FROM_CART_FAILURE",
  FETCH_USER_CART_START: "FETCH_USER_CART_START",
  FETCH_USER_CART_SUCCESS: "FETCH_USER_CART_SUCCESS",
  FETCH_USER_CART_FAILURE: "FETCH_USER_CART_FAILURE",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
};

export default CartActionTypes;
