const AdminActionTypes = {
  GET_ALL_BOOKINGS_START: "GET_ALL_BOOKINGS_START",
  GET_ALL_BOOKINGS_SUCCESS: "GET_ALL_BOOKINGS_SUCCESS",
  GET_ALL_BOOKINGS_FAILURE: "GET_ALL_BOOKINGS_FAILURE",
};

export default AdminActionTypes;
