const AdminActionTypes = {
  GET_ALL_BOOKINGS_START: "GET_ALL_BOOKINGS_START",
  GET_ALL_BOOKINGS_SUCCESS: "GET_ALL_BOOKINGS_SUCCESS",
  GET_ALL_BOOKINGS_FAILURE: "GET_ALL_BOOKINGS_FAILURE",

  GET_ALL_EMPLOYEES_START: "GET_ALL_EMPLOYEES_START",
  GET_ALL_EMPLOYEES_SUCCESS: "GET_ALL_EMPLOYEES_SUCCESS",
  GET_ALL_EMPLOYEES_FAILURE: "GET_ALL_EMPLOYEES_FAILURE",

  UPDATE_EMPLOYEE_START: "UPDATE_EMPLOYEE_START",
  UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_FAILURE: "UPDATE_EMPLOYEE_FAILURE",

  GET_EMPLOYEE_START: "GET_EMPLOYEE_START",
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
  GET_EMPLOYEE_FAILURE: "GET_EMPLOYEE_FAILURE",
};

export default AdminActionTypes;
