const bookingActionTypes = {
  GET_CHECKOUT_SESSION_START: "GET_CHECKOUT_SESSION_START",
  GET_CHECKOUT_SESSION: "GET_CHECKOUT_SESSION",
  GET_USER_BOOKINGS_START: "GET_USER_BOOKINGS_START",
  GET_USER_BOOKINGS_SUCCESS: "GET_USER_BOOKINGS_SUCCESS",
  GET_USER_BOOKINGS_FAILURE: "GET_USER_BOOKINGS_FAILURE",
};

export default bookingActionTypes;
