const bookingActionTypes = {
  GET_CHECKOUT_SESSION_START: "GET_CHECKOUT_SESSION_START",
  GET_CHECKOUT_SESSION: "GET_CHECKOUT_SESSION",
  GET_USER_BOOKINGS: "GET_USER_BOOKINGS",
};

export default bookingActionTypes;
