const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGIN_CURRENT_USER_START: "LOGIN_CURRENT_USER_START",
  LOGIN_CURRENT_USER_SUCCESS: "LOGIN_CURRENT_USER_SUCCESS",
  LOGIN_CURRENT_USER_FAILURE: "LOGIN_CURRENT_USER_FAILURE",
  SIGNUP_CURRENT_USER_START: "SIGNUP_CURRENT_USER_START",
  SIGNUP_CURRENT_USER_SUCCESS: "SIGNUP_CURRENT_USER_SUCCESS",
  SIGNUP_CURRENT_USER_FAILURE: "SIGNUP_CURRENT_USER_FAILURE",
  LOGOUT_CURRENT_USER_START: "LOGOUT_CURRENT_USER_START",
  LOGOUT_CURRENT_USER_SUCCESS: "LOGOUT_CURRENT_USER_SUCCESS",
  LOGOUT_CURRENT_USER_FAILURE: "LOGOUT_CURRENT_USER_FAILURE",
  TOGGLE_USER_OPTIONS_HIDDEN: "TOGGLE_USER_OPTIONS_HIDDEN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
  CANCEL_RESET_PASSWORD_PROCESS: "CANCEL_RESET_PASSWORD_PROCESS",
};

export default UserActionTypes;
