const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGIN_CURRENT_USER_START: "LOGIN_CURRENT_USER_START",
  LOGIN_CURRENT_USER_SUCCESS: "LOGIN_CURRENT_USER_SUCCESS",
  LOGIN_CURRENT_USER_FAILURE: "LOGIN_CURRENT_USER_FAILURE",
  SIGNUP_CURRENT_USER_START: "SIGNUP_CURRENT_USER_START",
  SIGNUP_CURRENT_USER_SUCCESS: "SIGNUP_CURRENT_USER_SUCCESS",
  SIGNUP_CURRENT_USER_FAILURE: "SIGNUP_CURRENT_USER_FAILURE",
  LOGOUT_CURRENT_USER_START: "LOGOUT_CURRENT_USER_START",
  LOGOUT_CURRENT_USER_SUCCESS: "LOGOUT_CURRENT_USER_SUCCESS",
  LOGOUT_CURRENT_USER_FAILURE: "LOGOUT_CURRENT_USER_FAILURE",
};

export default UserActionTypes;
